### ISSUE TITLE
CppCheck Parse Error "missingInclude"

### ISSUE THREAD

**Issue by cplussharp** [jbenden/vscode-c-cpp-flylint#44]
The line "    information missingInclude: Cppcheck cannot find all the include files (use --check-config for details)" always throws a parse error for me (on Windows 10)

This line should not do this and in the tests everythings works as expected. I'm not sure what the problem is here.

**Comment by jbenden** [comment]
Should be now fixed in `master`; by adjusting the regexp.

**Comment by cplussharp** [comment]
This was also my first thought ;). But sadly this didn't fix the problem. :(
I'm not sure what the problem is, because the line is the same as in the test. Maybe a UTF-8 Problem?

**Comment by cplussharp** [comment]
Thanks, with commit 4d08ffb it's working again.
