### ISSUE TITLE
Cannot ignore folder

### ISSUE THREAD

**Issue by linonetwo** [jbenden/vscode-c-cpp-flylint#57]
I tried `"c-cpp-flylint.excludeFromWorkspacePaths": ["3rdParty", "CMakeFiles"],` but it still checking those folders, and cpu usage is always 100%.

**Comment by Veetaha** [comment]
The same issue here

**Comment by seron** [comment]
I have this problem with the .git folder.

**Comment by jbenden** [comment]
Hello,

Would someone with this problem please post their configuration? I am not sure what is expanding all of them directories, into include parameters...

Thanks,
-Joe

**Comment by jbenden** [comment]
I believe this to be fixed in the mentioned commit. There was a section of code that build include path arguments, which did not check excluded items.

**Comment by dzid26** [comment]
I have following path: "/home/user/**workspace**/includes/hal".  I want to exclude _hal_ folder. 

If exclude absolute path, it works. But I would prefer something shorter.  

`"hal"` or `*/hal"` or "`includes/hal"` , `"${workspaceFolder}/includes/hal"` do not work.

**Comment by jbenden** [comment]
Hi,

Git-style globs should work, so try `includes/**/hal` or `includes/hal/**/*`.

Best regards,
-Joe

**Comment by dzid26** [comment]
Unfortunately none of these work. 
Also, I didn't mention, _hal_ folder doesn't have any subfolders. It's a single folder I want to get rid of. 
So really I would imagine `includes/hal` should be enough. 

I also tried `home/**/hal` or `home/*/*/*/hal` to get closer to the absolute path that works, but that didn't work either. 

This may not work, because I think include paths from c_cpp_properties.json come as absolute paths, i.e. `/home/user/workspace/includes/hal`. 
And we are trying to match exclude path to the beginning of the absolute path: https://github.com/jbenden/vscode-c-cpp-flylint/blob/138c5a5bbb49bf93af23cbae4d516c97b8d1631d/server/src/server.ts#L245 Shouldn't it be `endsWith()` or `includes()` ?

**Comment by jbenden** [comment]
So, what about adding it as `${workspaceRoot}/includes/hal/*`?

**Comment by dzid26** [comment]
I have following entries in `.vscode/settings.json`.

This work:
```
		"c-cpp-flylint.excludeFromWorkspacePaths": [
			".git",
			".vscode",
			"/home/dzid26/workspace/includes/hal"
		]
```
But this doesn't:
```
		"c-cpp-flylint.excludeFromWorkspacePaths": [
			".git",
			".vscode",
			"${workspaceRoot}/includes/hal/*"
		]
```

**Comment by jbenden** [comment]
Apparently, I just need to go back to bed... :) I'm so sorry - thanks for hanging in there!

So the matching of the `excludeFromWorkspacePaths` setting does not use glob nor regexp matching. It normalizes all paths to full absolute paths, and then proceeds to prefix match items from this config setting against the current workspace working file.

I think we actually want `${workspaceFolder}/include/hal` to work, yes? This would fix the need to specify the full, absolute, non-portable path within your configuration.

**Comment by dzid26** [comment]
Yes, `"${workspaceFolder}/include/hal"`, would do the job. 

I wonder whether excluding `.git` actually works if this is matching prefixes. I haven't checked thoroughly.

**Comment by jbenden** [comment]
@dzid26 I pushed a new version out with the change! Thanks so much!

**Comment by dzid26** [comment]
Thanks, it works for me. 

Though the debug output became bloated with repetitive statements.  
Shouldn't the _exclude normalization_  `_.each(currentSettings['c-cpp-flylint'].excludeFromWorkspacePaths, (excludedPath: string) => {` be executed only once outside the include loop `_.forEach(platformConfig.includePath, (ipath: string) => {`  ?

The log
``` 
Path: ${workspaceFolder}/**  VALUE: /home/dzid_/openpilot/panda/**  Globbed is: /home/dzid_/openpilot/panda/__pycache__,/home/dzid_/openpilot/panda/board,/home/dzid_/openpilot/panda/boardesp,/home/dzid_/openpilot/panda/certs,/home/dzid_/openpilot/panda/common,/home/dzid_/openpilot/panda/crypto,/home/dzid_/openpilot/panda/docs,/home/dzid_/openpilot/panda/drivers,/home/dzid_/openpilot/panda/examples,/home/dzid_/openpilot/panda/python,/home/dzid_/openpilot/panda/release,/home/dzid_/openpilot/panda/tests,/home/dzid_/openpilot/panda/board/__pycache__,/home/dzid_/openpilot/panda/board/boards,/home/dzid_/openpilot/panda/board/drivers,/home/dzid_/openpilot/panda/board/generated_dependencies,/home/dzid_/openpilot/panda/board/inc,/home/dzid_/openpilot/panda/board/obj,/home/dzid_/openpilot/panda/board/pedal,/home/dzid_/openpilot/panda/board/safety,/home/dzid_/openpilot/panda/board/tests,/home/dzid_/openpilot/panda/board/tools,/home/dzid_/openpilot/panda/boardesp/include,/home/dzid_/openpilot/panda/boardesp/obj,/home/dzid_/openpilot/panda/drivers/linux,/home/dzid_/openpilot/panda/drivers/windows,/home/dzid_/openpilot/panda/examples/__pycache__,/home/dzid_/openpilot/panda/python/__pycache__,/home/dzid_/openpilot/panda/tests/__pycache__,/home/dzid_/openpilot/panda/tests/automated,/home/dzid_/openpilot/panda/tests/build,/home/dzid_/openpilot/panda/tests/development,/home/dzid_/openpilot/panda/tests/gmbitbang,/home/dzid_/openpilot/panda/tests/language,/home/dzid_/openpilot/panda/tests/linter_python,/home/dzid_/openpilot/panda/tests/misra,/home/dzid_/openpilot/panda/tests/pedal,/home/dzid_/openpilot/panda/tests/safety,/home/dzid_/openpilot/panda/tests/safety_replay,/home/dzid_/openpilot/panda/board/pedal/obj,/home/dzid_/openpilot/panda/drivers/linux/test,/home/dzid_/openpilot/panda/drivers/windows/ECUsim CLI,/home/dzid_/openpilot/panda/drivers/windows/ECUsim DLL,/home/dzid_/openpilot/panda/drivers/windows/docs,/home/dzid_/openpilot/panda/drivers/windows/panda,/home/dzid_/openpilot/panda/drivers/windows/panda Driver Package,/home/dzid_/openpilot/panda/drivers/windows/pandaJ2534DLL,/home/dzid_/openpilot/panda/drivers/windows/pandaJ2534DLL Test,/home/dzid_/openpilot/panda/drivers/windows/panda_playground,/home/dzid_/openpilot/panda/drivers/windows/panda_shared,/home/dzid_/openpilot/panda/drivers/windows/redist,/home/dzid_/openpilot/panda/drivers/windows/test certs,/home/dzid_/openpilot/panda/tests/automated/__pycache__,/home/dzid_/openpilot/panda/tests/safety/__pycache__,/home/dzid_/openpilot/panda/tests/safety_replay/__pycache__
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/__pycache__
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/boardesp
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/certs
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/common
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/crypto
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/docs
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/drivers
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/examples
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/python
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/release
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/tests
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/__pycache__
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/boards
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/drivers
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/generated_dependencies
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/obj
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/pedal
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/safety
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/tests
Exclude Path: .git  VALUE: .git  Normalized: .git
Exclude Path: .vscode  VALUE: .vscode  Normalized: .vscode
Exclude Path: ${workspaceFolder}/board/inc  VALUE: /home/dzid_/openpilot/panda/board/inc  Normalized: /home/dzid_/openpilot/panda/board/inc
Adding path: /home/dzid_/openpilot/panda/board/tools
...
```

**Comment by grintroy** [comment]
This is still an issue on my system (v1.15.0). I have

```json
"c-cpp-flylint.excludeFromWorkspacePaths": [
		"${workspaceFolder}/build"
	],
```

in my `settings.json`, and it still floods my Problems window with files from the `build` folder. I tried `${workspaceFolder}/build/*`, `${workspaceFolder}/build/**`, `/build`, `build`, `build/`, and other versions with the asterisks, and still no luck.

Also, I have the build directory excluded in my `.gitignore` file, and I assumed that the extension would respect that, but the issue still persists.
